version = 0.1

[default.deploy.parameters]
stack_name = "projeto-4-aws"
resolve_s3 = true
s3_prefix = "projeto-4-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "us-east-1"
